### ISSUE TITLE
can we generate psi/si information from this? 

### ISSUE THREAD

**Issue by sachin0606** [mkrufky/node-dvbtee#20]
Hi, 

can we use this application as psi/si server?

**Comment by mkrufky** [comment]
node-dvbtee will parse any transport stream and emit JSON PSIP object events.  It's written with the idea in mind of solving the stream parsing details so that developers can spend their time writing better server code.

So yes, you can indeed use this to create a server.

**Comment by sachin0606** [comment]
can you provide info to create server so will try my level best to create server...

**Comment by mkrufky** [comment]
There is an example repository at [github.com/mkrufky/dvbtee-express](https://github.com/mkrufky/dvbtee-express)
